process healthgate {
    run /usr/bin/env python3 /etc/anycast/health.py;
    encoder text;
}

neighbor 10.89.7.20 {
    router-id 10.89.7.10;
    local-address 10.89.7.10;
    local-as 65010;
    peer-as 65020;

    api {
        processes [ healthgate ];
    }
}
