#!/usr/bin/env bash
# build-rescue-initrd.sh — the "known-good rescue initramfs" the initrd-swap track
# swaps INTO a UKI's .initrd (Spike 9).
#
# Derived at run time, never cached (the repo's rule): a small newc cpio with
# DISTINCT members (so the swap is visibly a change from the UKI's own initrd),
# built with the host's own GNU cpio, so `cpio -itv` is a faithful oracle of the
# members cpio.fth must walk after the swap. It must be ≤ the UKI's .initrd raw
# capacity (512 bytes here) to swap IN PLACE — a larger one is the TOO-BIG control.
#
# It ALSO emits a Forth source that compiles those bytes into the dictionary —
# `rescue-cpio ( -- adr len )` — because the swap needs the replacement bytes in
# firmware memory WITHOUT a second load buffer: `$setenv load-base` + a second
# `load` is a unix-door-only trick (and x86 relocates its addresses), so the
# cross-arch way is to carry the bytes in the dictionary, which is ordinary Forth
# memory on every arch. Generated from the SAME cpio, so it cannot drift from it.
#
# Usage: build-rescue-initrd.sh <out.cpio> <out.fth>
set -eu
OUTC="${1:?usage: build-rescue-initrd.sh <out.cpio> <out.fth>}"
OUTF="${2:?usage: build-rescue-initrd.sh <out.cpio> <out.fth>}"
command -v cpio >/dev/null || { echo "cpio not installed (GNU cpio) — the swap oracle" >&2; exit 1; }
command -v od   >/dev/null || { echo "od not installed (coreutils)" >&2; exit 1; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
printf 'SOS help\n'  > "$TMP/rescue"    # a distinct member name (not in the UKI's initrd)
printf '#!/bin/sh\n' > "$TMP/init"      # a second, so the swap shows >1 member changed
( cd "$TMP" && printf '%s\n' rescue init | cpio -o -H newc 2>/dev/null ) > "$OUTC"
[[ -s "$OUTC" ]] || { echo "cpio produced an empty rescue archive at $OUTC" >&2; exit 1; }
sz="$(stat -c%s "$OUTC")"
(( sz <= 512 )) || { echo "the rescue cpio is $sz bytes (> 512) — it will not swap into the .initrd section in place" >&2; exit 1; }

# emit the dictionary-data Forth: `create rescue-data <bytes> c,` then rescue-cpio.
{ echo '\ GENERATED by fixtures/initrd-swap/build-rescue-initrd.sh — do not edit.'
  echo '\ The rescue initramfs bytes, compiled into the dictionary so the swap needs'
  echo '\ no second load buffer (cross-arch: the dictionary is ordinary Forth memory).'
  echo 'hex'
  echo 'create rescue-data'
  od -An -v -tx1 "$OUTC" | tr -s ' ' '\n' | grep -vE '^$' \
    | awk '{printf "%s c, ", $1; if (NR % 16 == 0) printf "\n"}'
  echo
  printf ': rescue-cpio ( -- adr len )  rescue-data %x ;\n' "$sz"
} > "$OUTF"
[[ -s "$OUTF" ]] || { echo "failed to emit the rescue Forth at $OUTF" >&2; exit 1; }
# VERIFY THE OUTCOME, not od's flag: the emitted Forth must encode EXACTLY sz bytes.
# od without -v collapses repeated bytes (the cpio's NUL padding) to `*` and would
# silently drop them; assert the count rather than trust that -v did its job.
nbytes="$(grep -oE '[0-9a-f]{2} c,' "$OUTF" | wc -l)"
(( nbytes == sz )) || { echo "the emitted Forth encodes $nbytes bytes, expected $sz — the byte extraction dropped or added bytes" >&2; exit 1; }
