#!/usr/bin/env bash
# build-detok-vocab.sh — recover the FCode DETOKENIZER as a loadable vocabulary.
#
# `detokenize` is one of only two audited words genuinely absent from the ROM
# (probe-dictionary.sh proves it). Its source IS in the tree, but a plain fload
# fails: detokeni.fth pulls three siblings through ${BP}, a BUILD-PATH variable
# that does not exist at the ok prompt.
#
# So flatten it — and note this is a dependency-ordered SPLICE, not a concat:
#   lines 1..52     of detokeni.fth
#   common.fth      (the `needs init-tables` dep at line 53)
#   lines 55..255   of detokeni.fth
#   primlist / sysprims / regcodes   (the three floads at lines 256-258)
#   lines 259..end  of detokeni.fth
# Naive concatenation gives undefined words.
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
WORKDIR="${OFW_WORKDIR:-$HOME/ofw-lab}"
SRC="${OFW_SRC:-$WORKDIR/openfirmware}"
OUT="$HERE/dsl/detok.fth"

[ -d "$SRC/ofw/fcode" ] || { echo "SKIP: no OFW source at $SRC (run the parent lab's build-ofw.sh)"; exit 77; }
python3 - "$SRC" "$OUT" <<'PY'
import sys, pathlib
src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
d = (src/"ofw/fcode/detokeni.fth").read_text(errors="replace").splitlines(True)
f = lambda p: (src/"ofw/fcode"/p).read_text(errors="replace")
text  = "".join(d[:52]) + f("common.fth") + "".join(d[54:255])
text += f("primlist.fth") + f("sysprims.fth") + f("regcodes.fth")
text += "".join(d[258:])
out.write_text("\\ GENERATED by build-detok-vocab.sh — do not edit; edit the splice instead.\n" + text)
print(f"wrote {out} ({text.count(chr(10))} lines spliced from 5 sources)")
PY
