#!/usr/bin/env bash
# maas-lab.sh — a miniature bare-metal control plane (Metal-as-a-Service).
#
# INCREMENT 1 (build-order step 1): the fleet registry + the full Ironic-faithful
# state machine as PURE STATE TRANSITIONS, `power`/`bootdev` passthrough to the
# BMC, guarded `cleaning`, `error`/`maintenance`, and `rescue`. The heavy actions
# (a real PXE install, the RAM inspection probe, dd-a-golden-image) are build
# steps 2–5; here every verb is verifiable HEADLESSLY, with no libvirt and no
# install, because all out-of-band effects go through one injectable seam:
#
#     MAAS_BMC   -> path to bmc-toolkit's bmc.sh (default: ../bmc-toolkit/bmc.sh),
#                   invoked as `$MAAS_BMC <node> <verb> ...` (node first).
#                   Tests point it at a mock that records calls + returns canned
#                   output, so the whole machine drives with zero rootful libvirt.
#
# See METAL_AS_A_SERVICE_LAB_PLAN.md (§3 state machine, §9 build order) and the
# lab README for the design. Ironic node-state model:
#   https://docs.openstack.org/ironic/latest/contributor/states.html
#
# Security posture (AUDIT.md): BMC creds live on loopback only (F1); the
# `cleaning` disk wipe is path-guarded and HANDED TO THE USER, never auto-run
# (F7); processes are killed by PID, never by pattern.
set -uo pipefail

MAAS_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly MAAS_DIR

# ── the BMC seam ────────────────────────────────────────────────────────────
# Default to the sibling bmc-toolkit; a test or a different fleet overrides it.
MAAS_BMC="${MAAS_BMC:-$MAAS_DIR/../bmc-toolkit/bmc.sh}"

die()  { printf 'maas: %s\n' "$*" >&2; exit 1; }
warn() { printf 'maas: %s\n' "$*" >&2; }
info() { printf '  - %s\n' "$*" >&2; }

# ── state directory resolution ──────────────────────────────────────────────
# Mirrors tools/control-pane's LAB_STATE_DIR logic so the two agree on one base
# (MAAS lives beside control-pane, which later renders its progress).
maas_state_root() {
    if [[ -n "${MAAS_STATE:-}" ]]; then printf '%s\n' "$MAAS_STATE"; return; fi
    local base
    if   [[ -n "${LAB_STATE_DIR:-}" ]]; then base="$LAB_STATE_DIR"
    elif [[ "$(id -u)" == 0 ]];         then base="/var/lib/lab-create"
    else base="${XDG_STATE_HOME:-$HOME/.local/state}/lab-create"; fi
    printf '%s/metal-as-a-service\n' "$base"
}
STATE_ROOT="$(maas_state_root)"
readonly STATE_ROOT
REG_BMC="$STATE_ROOT/fleet-bmc.toml"   # generated bmc-toolkit registry for bmc.sh

node_dir()  { printf '%s/%s\n' "$STATE_ROOT" "$1"; }
node_exists() { [[ -d "$(node_dir "$1")" ]]; }
require_node() { node_exists "$1" || die "no such node '$1' (enroll it first: maas-lab.sh enroll $1 ...)"; }

# ── registry primitives (atomic single-value files) ─────────────────────────
# The registry is a directory tree: one dir per node, one small file per field.
# Atomic writes (tmp + mv) keep `state` always readable and never half-written.
_write() {  # _write <node> <field> <value>
    local d; d="$(node_dir "$1")"; mkdir -p "$d"
    printf '%s\n' "$3" > "$d/.$2.tmp" && mv "$d/.$2.tmp" "$d/$2"
}
_read() {   # _read <node> <field> [default]
    local f; f="$(node_dir "$1")/$2"
    if [[ -f "$f" ]]; then cat "$f"; else printf '%s' "${3:-}"; fi
}
read_state() { _read "$1" state ""; }

# The single choke-point for every state change: validates nothing here (callers
# guard preconditions), records the transition in history, writes atomically.
set_state() {  # set_state <node> <new-state> <verb>
    local node="$1" new="$2" verb="$3" old ts
    old="$(read_state "$node")"; old="${old:-<new>}"
    ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    _write "$node" state "$new"
    printf '%s  %-11s -> %-11s (%s)\n' "$ts" "$old" "$new" "$verb" \
        >> "$(node_dir "$node")/history.log"
}

# Precondition guard: current state must be one of the allowed set, else refuse
# with a SPECIFIC message naming the required state (test convention: name the
# defect, not "illegal transition").
require_state() {  # require_state <node> <verb> <allowed>...
    local node="$1" verb="$2"; shift 2
    local cur; cur="$(read_state "$node")"
    local a
    for a in "$@"; do [[ "$cur" == "$a" ]] && return 0; done
    die "cannot '$verb' node '$node' from state '${cur:-<none>}' — needs one of: $*"
}

# ── the BMC seam ────────────────────────────────────────────────────────────
# All power/bootdev/sol reach the node through bmc-toolkit, using MAAS's own
# generated registry. A mock bmc.sh (tests) ignores the registry entirely.
bmc() {  # bmc <node> <verb> [args...]
    BMC_REGISTRY="$REG_BMC" "$MAAS_BMC" "$@"
}

# Regenerate the bmc-toolkit registry from every enrolled node (all vbmcd on
# loopback). Called on enroll so `bmc.sh` can resolve MAAS's node names.
regen_bmc_registry() {
    local tmp="$REG_BMC.tmp" d n
    mkdir -p "$STATE_ROOT"
    {
        printf '# Generated by maas-lab.sh — do not hand-edit (regenerated on enroll).\n'
        printf '# bmc-toolkit registry: MAAS fleet, all vbmcd on loopback (F1).\n\n'
        for d in "$STATE_ROOT"/*/; do
            [[ -f "$d/state" ]] || continue
            n="$(basename "$d")"
            printf '[[node]]\n'
            printf 'name      = "%s"\n' "$n"
            printf 'backend   = "vbmcd"\n'
            printf 'domain    = "%s"\n' "$(_read "$n" domain "$n")"
            printf 'uri       = "%s"\n' "$(_read "$n" uri qemu:///system)"
            printf 'ipmi_host = "%s"\n' "$(_read "$n" bmc_host 127.0.0.1)"
            printf 'ipmi_port = %s\n'   "$(_read "$n" bmc_port 623)"
            printf 'ipmi_user = "%s"\n' "$(_read "$n" bmc_user admin)"
            printf 'ipmi_pass = "%s"\n\n' "$(_read "$n" bmc_pass password)"
        done
    } > "$tmp" && mv "$tmp" "$REG_BMC"
}

# ═══════════════════════════════════════════════════════════════════════════
# Verbs
# ═══════════════════════════════════════════════════════════════════════════

# enroll — register a node into the fleet (∅ -> enrolled).
cmd_enroll() {
    local node="" domain="" bmc_port="" mac="" firmware="bios" uri="qemu:///system"
    local bmc_user="admin" bmc_pass="password" bmc_host="127.0.0.1"
    node="${1:?usage: enroll <node> --bmc-port P [--domain D --mac M --firmware bios|uefi]}"; shift
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --domain)   domain="$2"; shift 2 ;;
            --bmc-port) bmc_port="$2"; shift 2 ;;
            --bmc-host) bmc_host="$2"; shift 2 ;;
            --bmc-user) bmc_user="$2"; shift 2 ;;
            --bmc-pass) bmc_pass="$2"; shift 2 ;;
            --mac)      mac="$2"; shift 2 ;;
            --firmware) firmware="$2"; shift 2 ;;
            --uri)      uri="$2"; shift 2 ;;
            *) die "enroll: unknown option '$1'" ;;
        esac
    done
    node_exists "$node" && die "node '$node' already enrolled (state=$(read_state "$node")); use 'show $node'"
    [[ -n "$bmc_port" ]] || die "enroll: --bmc-port is required (the node's loopback IPMI port, e.g. 6230)"
    [[ "$firmware" == bios || "$firmware" == uefi ]] || die "enroll: --firmware must be 'bios' or 'uefi'"
    [[ -n "$domain" ]] || domain="$node"
    mkdir -p "$(node_dir "$node")"
    _write "$node" domain "$domain"
    _write "$node" bmc_port "$bmc_port"
    _write "$node" bmc_host "$bmc_host"
    _write "$node" bmc_user "$bmc_user"
    _write "$node" bmc_pass "$bmc_pass"
    _write "$node" uri "$uri"
    [[ -n "$mac" ]] && _write "$node" mac "$mac"
    _write "$node" firmware "$firmware"
    set_state "$node" enrolled enroll
    regen_bmc_registry
    printf 'enrolled %s (domain=%s bmc=%s:%s firmware=%s)\n' \
        "$node" "$domain" "$bmc_host" "$bmc_port" "$firmware" >&2
}

# manage — verify BMC creds, make the node manageable (enrolled|error -> manageable).
# The `verifying` state is passed THROUGH so the saga shows in history; a BMC that
# doesn't answer sends the node to `error`, not a silent hang.
cmd_manage() {
    local node="${1:?usage: manage <node>}"; require_node "$node"
    require_state "$node" manage enrolled error
    set_state "$node" verifying manage
    if bmc "$node" power status >/dev/null 2>&1; then
        set_state "$node" manageable manage
        printf 'manageable %s (BMC creds verified)\n' "$node" >&2
    else
        set_state "$node" error manage
        die "verify failed for '$node': BMC did not answer 'power status' — node -> error (retry after fixing the BMC)"
    fi
}

# inspect — populate schedulable facts (manageable -> manageable, + facts).
# INCREMENT 1: facts are injected via --facts for headless testing; the REAL RAM
# inspection probe (busybox /init POSTs CPU/RAM/MAC to :8181) is build step 2.
cmd_inspect() {
    local node="" facts=""
    node="${1:?usage: inspect <node> [--facts facts.json]}"; shift
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --facts) facts="$2"; shift 2 ;;
            *) die "inspect: unknown option '$1'" ;;
        esac
    done
    require_node "$node"
    require_state "$node" inspect manageable
    if [[ -n "$facts" ]]; then
        [[ -f "$facts" ]] || die "inspect: --facts file not found: $facts"
        cp -- "$facts" "$(node_dir "$node")/facts.json"
        info "recorded schedulable facts from $facts"
    else
        printf '{"status":"pending","note":"real RAM probe lands in build step 2"}\n' \
            > "$(node_dir "$node")/facts.json"
        info "no --facts given; wrote a pending placeholder (real inspection probe = build step 2)"
    fi
    set_state "$node" manageable inspect   # re-affirm; records the inspect in history
    printf 'inspected %s\n' "$node" >&2
}

# provide — clean the node and make it schedulable (manageable -> available).
# Passes THROUGH `cleaning`: a disk wipe is a SECURITY BOUNDARY (data remanence),
# not housekeeping. A node with a real backing disk STAYS in `cleaning` until the
# operator runs the handed-over wipe and re-runs with --wiped — the machine never
# auto-runs a destructive command (F7). A diskless (ramdisk) node cleans as a
# genuine no-op.
cmd_provide() {
    local node="" wiped=0
    node="${1:?usage: provide <node> [--wiped]}"; shift
    while [[ $# -gt 0 ]]; do
        case "$1" in --wiped) wiped=1; shift ;; *) die "provide: unknown option '$1'" ;; esac
    done
    require_node "$node"
    require_state "$node" provide manageable cleaning
    set_state "$node" cleaning provide
    if wipe_disk "$node" "$wiped"; then
        set_state "$node" available provide
        printf 'available %s (cleaned; schedulable)\n' "$node" >&2
    else
        die "node '$node' stays in 'cleaning' until its disk is wiped — do the wipe above, then: provide $node --wiped"
    fi
}

# wipe_disk — the `cleaning` action. NEVER runs a destructive verb itself; it
# prints the exact, path-guarded command for the operator to run (F7 + the repo
# rule: destructive deletes are handed over, not auto-executed).
# Returns 0 = clean (no disk, or operator-confirmed); 2 = wipe pending (handed
# over). Refuses (exit 1) a disk outside the lab-owned allow-list.
wipe_disk() {  # wipe_disk <node> <confirmed:0|1>
    local node="$1" confirmed="${2:-0}" disk
    disk="$(_read "$node" disk "")"
    if [[ -z "$disk" ]]; then
        info "cleaning '$node': no backing disk registered — wipe is a no-op (ramdisk-style node)"
        return 0
    fi
    case "$disk" in
        /var/lib/libvirt/images/*|"$STATE_ROOT"/*) : ;;   # allow-list: lab-owned paths only
        *) die "cleaning refused: disk '$disk' is outside the lab's allow-list — will not wipe" ;;
    esac
    if [[ "$confirmed" == 1 ]]; then
        info "operator confirmed the wipe of $disk (--wiped)"
        return 0
    fi
    warn "cleaning '$node' needs a disk wipe (data remanence). NOT auto-run — run this yourself:"
    printf '    sudo blkdiscard -f %q  ||  sudo dd if=/dev/zero of=%q bs=1M status=progress\n' \
        "$disk" "$disk" >&2
    return 2
}

# deploy — put an OS on the node (available -> active).
# INCREMENT 1: this is a STATE-ONLY transition that records the chosen driver +
# image and passes through `deploying`. The real deploy mechanisms (install/
# ramdisk/image drivers) and the health-gated activation + A/B rollback are build
# steps 3–5 — deploy here does NOT boot an OS, and says so.
cmd_deploy() {
    local node="" driver="" image=""
    node="${1:?usage: deploy <node> --driver install|ramdisk|image [--image NAME]}"; shift
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --driver) driver="$2"; shift 2 ;;
            --image)  image="$2"; shift 2 ;;
            *) die "deploy: unknown option '$1'" ;;
        esac
    done
    require_node "$node"
    require_state "$node" deploy available
    case "$driver" in
        install|ramdisk|image|image+measured) : ;;
        "") die "deploy: --driver is required (install|ramdisk|image|image+measured)" ;;
        *)  die "deploy: unknown driver '$driver' (install|ramdisk|image|image+measured)" ;;
    esac
    set_state "$node" deploying deploy
    _write "$node" driver "$driver"
    [[ -n "$image" ]] && _write "$node" image "$image"
    # A/B slots: today's image becomes 'previous' before the new one lands (the
    # rollback mechanic; the health gate that USES it is build step 3).
    local prev; prev="$(_read "$node" image "")"
    [[ -n "$prev" && -n "$image" && "$prev" != "$image" ]] && _write "$node" previous_image "$prev"
    info "driver=$driver image=${image:-<none>} — STATE-ONLY in increment 1"
    info "real boot + health-gated activation (§4b) lands in build step 3"
    set_state "$node" active deploy
    printf 'active %s (driver=%s image=%s)\n' "$node" "$driver" "${image:-<none>}" >&2
}

# rescue — boot a recovery ramdisk to fix a broken node (active -> rescue).
# INCREMENT 1: records intent + flips bootdev; the real root-password-reset
# recovery ramdisk boot is a fast-follow.
cmd_rescue() {
    local node="${1:?usage: rescue <node>}"; require_node "$node"
    require_state "$node" rescue active
    set_state "$node" rescuing rescue
    bmc "$node" bootdev pxe >/dev/null 2>&1 || info "(bootdev pxe not confirmed — headless/mock)"
    info "recovery ramdisk (root-password-reset idioms) boots here — fast-follow"
    set_state "$node" rescue rescue
    printf 'rescue %s (recovery mode)\n' "$node" >&2
}

# unrescue — leave rescue, back to service (rescue -> active).
cmd_unrescue() {
    local node="${1:?usage: unrescue <node>}"; require_node "$node"
    require_state "$node" unrescue rescue
    bmc "$node" bootdev disk >/dev/null 2>&1 || true
    set_state "$node" active unrescue
    printf 'active %s (left rescue)\n' "$node" >&2
}

# release — return a node to the pool (active|rescue -> available), via cleaning.
# Same F7 wipe guard as provide: a node with a real disk stays in `cleaning`
# until --wiped.
cmd_release() {
    local node="" wiped=0
    node="${1:?usage: release <node> [--wiped]}"; shift
    while [[ $# -gt 0 ]]; do
        case "$1" in --wiped) wiped=1; shift ;; *) die "release: unknown option '$1'" ;; esac
    done
    require_node "$node"
    require_state "$node" release active rescue cleaning
    set_state "$node" deleting release
    # a released node's slots are stale — forget them so the next tenant starts clean
    rm -f "$(node_dir "$node")/driver" "$(node_dir "$node")/image" \
          "$(node_dir "$node")/previous_image" 2>/dev/null || true
    set_state "$node" cleaning release
    if wipe_disk "$node" "$wiped"; then
        set_state "$node" available release
        printf 'available %s (released to pool)\n' "$node" >&2
    else
        die "node '$node' stays in 'cleaning' until its disk is wiped — do the wipe above, then: release $node --wiped"
    fi
}

# maintenance — pull a node out of scheduling (any -> maintenance), remembering
# the state to return to. unmaintenance restores it.
cmd_maintenance() {
    local node="${1:?usage: maintenance <node>}"; require_node "$node"
    local cur; cur="$(read_state "$node")"
    [[ "$cur" == maintenance ]] && die "node '$node' is already in maintenance"
    _write "$node" prior_state "$cur"
    set_state "$node" maintenance maintenance
    printf 'maintenance %s (was %s)\n' "$node" "$cur" >&2
}
cmd_unmaintenance() {
    local node="${1:?usage: unmaintenance <node>}"; require_node "$node"
    require_state "$node" unmaintenance maintenance
    local prior; prior="$(_read "$node" prior_state manageable)"
    set_state "$node" "$prior" unmaintenance
    rm -f "$(node_dir "$node")/prior_state" 2>/dev/null || true
    printf '%s %s (out of maintenance)\n' "$prior" "$node" >&2
}

# retry — re-drive a failed node (error -> manageable via manage's verify).
cmd_retry() {
    local node="${1:?usage: retry <node>}"; require_node "$node"
    require_state "$node" retry error
    cmd_manage "$node"
}

# power / bootdev / console — passthrough to the BMC (the seam).
cmd_power() {
    local node="${1:?usage: power <node> {on|off|cycle|status}}"; require_node "$node"
    local sub="${2:?usage: power <node> {on|off|cycle|status}}"
    bmc "$node" power "$sub"
}
cmd_bootdev() {
    local node="${1:?usage: bootdev <node> {pxe|disk|cdrom}}"; require_node "$node"
    local sub="${2:?usage: bootdev <node> {pxe|disk|cdrom}}"
    bmc "$node" bootdev "$sub"
}
cmd_console() {  # honest SOL substitute = libvirt serial via bmc-toolkit's `sol`
    local node="${1:?usage: console <node>}"; require_node "$node"
    bmc "$node" sol
}

# ── readers ─────────────────────────────────────────────────────────────────
cmd_state() { local node="${1:?usage: state <node>}"; require_node "$node"; read_state "$node"; }

cmd_show() {
    local node="${1:?usage: show <node>}"; require_node "$node"
    local d; d="$(node_dir "$node")"
    printf 'node        %s\n' "$node"
    printf 'state       %s\n' "$(read_state "$node")"
    printf 'domain      %s\n' "$(_read "$node" domain -)"
    printf 'bmc         %s:%s (%s/%s)\n' "$(_read "$node" bmc_host -)" "$(_read "$node" bmc_port -)" \
        "$(_read "$node" bmc_user -)" "$(_read "$node" bmc_pass -)"
    printf 'firmware    %s\n' "$(_read "$node" firmware -)"
    printf 'driver      %s\n' "$(_read "$node" driver -)"
    printf 'image       %s (previous: %s)\n' "$(_read "$node" image -)" "$(_read "$node" previous_image -)"
    [[ -f "$d/facts.json" ]] && printf 'facts       %s\n' "$(cat "$d/facts.json")"
    if [[ -f "$d/history.log" ]]; then
        printf 'history:\n'; sed 's/^/  /' "$d/history.log"
    fi
}

cmd_list() {
    local json=0; [[ "${1:-}" == "--json" ]] && json=1
    local d n st dr
    if [[ $json -eq 1 ]]; then
        printf '['
        local first=1
        for d in "$STATE_ROOT"/*/; do
            [[ -f "$d/state" ]] || continue
            n="$(basename "$d")"; st="$(read_state "$n")"; dr="$(_read "$n" driver "")"
            [[ $first -eq 1 ]] || printf ','; first=0
            printf '{"name":"%s","state":"%s","driver":"%s"}' "$n" "$st" "$dr"
        done
        printf ']\n'
        return
    fi
    [[ -d "$STATE_ROOT" ]] || { printf 'no nodes enrolled (state dir: %s)\n' "$STATE_ROOT" >&2; return; }
    local any=0
    printf '%-10s %-12s %-10s %s\n' NODE STATE DRIVER DOMAIN
    for d in "$STATE_ROOT"/*/; do
        [[ -f "$d/state" ]] || continue
        any=1; n="$(basename "$d")"
        printf '%-10s %-12s %-10s %s\n' "$n" "$(read_state "$n")" \
            "$(_read "$n" driver -)" "$(_read "$n" domain -)"
    done
    [[ $any -eq 1 ]] || printf 'no nodes enrolled (state dir: %s)\n' "$STATE_ROOT" >&2
}

usage() {
    cat >&2 <<'EOF'
maas-lab.sh — miniature bare-metal control plane (increment 1: registry + state machine)

Lifecycle verbs (Ironic-faithful state machine):
  enroll <node> --bmc-port P [--domain D --mac M --firmware bios|uefi]   (∅ -> enrolled)
  manage <node>                          enrolled|error -> manageable (verifies BMC)
  inspect <node> [--facts f.json]        manageable -> manageable (+schedulable facts)
  provide <node> [--wiped]               manageable -> available (via cleaning/wipe)
  deploy <node> --driver D [--image I]   available -> active (install|ramdisk|image|image+measured)
  rescue <node> / unrescue <node>        active <-> rescue
  release <node> [--wiped]               active|rescue -> available (via cleaning)
  maintenance <node> / unmaintenance <node>   any <-> maintenance
  retry <node>                           error -> manageable

Out-of-band (passthrough to bmc-toolkit's bmc.sh via MAAS_BMC):
  power <node> {on|off|cycle|status}     bootdev <node> {pxe|disk|cdrom}     console <node>

Inspect the registry:
  list [--json]     state <node>     show <node>

Increment 1 is headless: set MAAS_BMC=<mock> to drive the whole machine with no libvirt.
State dir: $STATE_ROOT (override with MAAS_STATE / LAB_STATE_DIR).
EOF
}

# ── dispatch ────────────────────────────────────────────────────────────────
main() {
    local verb="${1:-}"; [[ $# -gt 0 ]] && shift
    case "$verb" in
        enroll)        cmd_enroll "$@" ;;
        manage)        cmd_manage "$@" ;;
        inspect)       cmd_inspect "$@" ;;
        provide)       cmd_provide "$@" ;;
        deploy)        cmd_deploy "$@" ;;
        rescue)        cmd_rescue "$@" ;;
        unrescue)      cmd_unrescue "$@" ;;
        release|undeploy) cmd_release "$@" ;;
        maintenance)   cmd_maintenance "$@" ;;
        unmaintenance) cmd_unmaintenance "$@" ;;
        retry)         cmd_retry "$@" ;;
        power)         cmd_power "$@" ;;
        bootdev)       cmd_bootdev "$@" ;;
        console|sol)   cmd_console "$@" ;;
        state)         cmd_state "$@" ;;
        show)          cmd_show "$@" ;;
        list)          cmd_list "$@" ;;
        ""|-h|--help|help) usage ;;
        *) die "unknown verb '$verb' (try: maas-lab.sh --help)" ;;
    esac
}
main "$@"
