#!/usr/bin/env bash
# netboot-chain.sh — make the PXE network ASK the control plane what each node boots.
#
# THE BUG THIS EXISTS TO FIX. The sibling lab's setup-pxe-net.sh installs ONE
# `boot.ipxe` for the whole network (`<bootp file='boot.ipxe'/>`) and bakes the payload
# into it: every node on vbmc-pxe boots the same thing. That is right for a single-node
# lab and catastrophic for a fleet — the deploy drivers write a per-node script at
# `<docroot>/maas/<node>.ipxe`, and with a baked boot.ipxe **nothing ever fetches it**.
# The node netboots the network default, the control plane waits for a marker that will
# never appear, and the only symptom is a timeout. (That is exactly how the first live
# run of run-e2e.sh failed, twice, in two different phases.)
#
# So: replace the baked boot.ipxe with a CHAIN. It resolves per node, in this order:
#
#   1. maas/${hostname}.ipxe    the node's own script. `hostname` comes from DHCP
#                               option 12, which dnsmasq sends because we add a
#                               `<host mac= name=/>` entry per node (create-fleet.sh).
#   2. maas/${net0/mac}.ipxe    same script keyed by MAC, for a node whose DHCP
#                               reservation is missing or whose firmware ignores
#                               option 12.
#   3. maas/default.ipxe        the unclaimed-node script: it does NOT boot something
#                               plausible. It says, on the console, that the control
#                               plane has nothing for this node and drops to the iPXE
#                               shell. A node booting the wrong OS quietly is a worse
#                               outcome than a node that stops and says why.
#
# Verbs:
#   install   write the chain into the TFTP root + the default script (needs sudo
#             for the TFTP root only — it lives under /var/lib/libvirt)
#   show      print what is currently installed
#
# Knobs (env): TFTP_DIR  MAAS_NETBOOT_DIR  MAAS_NETBOOT_PORT  NET
set -uo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TFTP_DIR="${TFTP_DIR:-/var/lib/libvirt/tftp-vbmc}"      # matches ../virtualbmc-ipmi-lab
DOCROOT="${MAAS_NETBOOT_DIR:-$HOME/netboot}"
PORT="${MAAS_NETBOOT_PORT:-8181}"                        # 8181 is intentional (SABnzbd owns 8080)
NET="${NET:-vbmc-pxe}"

die()  { printf 'netboot-chain: %s\n' "$*" >&2; exit 1; }
info() { printf '  - %s\n' "$*" >&2; }

# The chain itself. Single-quoted heredoc: ${hostname}, ${net0/mac} and ${next-server}
# are iPXE settings resolved on the NODE, not shell variables — a double-quoted heredoc
# would try to expand them here and `${next-server}` is not even valid bash.
chain_script() {
    cat <<'IPXE'
#!ipxe
# generated by examples/metal-as-a-service/netboot-chain.sh — do not hand-edit
# This script asks the control plane what THIS node should boot. It never bakes in
# a payload: the answer lives in maas/<node>.ipxe, written by maas-lab.sh.
:retry
dhcp || goto retry
set base http://${next-server}:@PORT@/maas
echo MAAS: resolving a boot script for ${hostname} (${net0/mac}) from ${base}
chain ${base}/${hostname}.ipxe || chain ${base}/${net0/mac}.ipxe || chain ${base}/default.ipxe || shell
IPXE
}

# The unclaimed-node script. It is deliberately a DEAD END that explains itself.
default_script() {
    cat <<'IPXE'
#!ipxe
# generated by examples/metal-as-a-service/netboot-chain.sh — do not hand-edit
echo
echo ================================================================
echo  MAAS: no boot script for this node.
echo
echo  The node asked for maas/${hostname}.ipxe and maas/${net0/mac}.ipxe.
echo  Either the control plane has written neither -- or one WAS fetched and
echo  then aborted. Scroll up: a script that fetched ok and then printed
echo  'Could not verify ... (https://ipxe.org/0227e13c)' is not missing, it
echo  REFUSED a payload whose signature did not match (imgverify).
echo
echo  Nothing will be booted either way: quietly booting SOMETHING would look
echo  like a successful deploy of the wrong thing, which is the failure this
echo  lab exists to make impossible.
echo
echo  On the control plane, one of:
echo    maas-lab.sh inspect <node> --boot          (introspection probe)
echo    maas-lab.sh deploy  <node> --driver ... --image ...
echo  then power-cycle this node.
echo ================================================================
echo
shell
IPXE
}

case "${1:-}" in

install)
    command -v sudo >/dev/null || die "sudo required to write the TFTP root ($TFTP_DIR)"
    [[ -d "$DOCROOT" ]] || die "PXE docroot not found: $DOCROOT (set MAAS_NETBOOT_DIR=)"

    # 1. the chain, into the TFTP root dnsmasq serves as <bootp file='boot.ipxe'/>.
    sudo mkdir -p "$TFTP_DIR" || die "could not create $TFTP_DIR"
    if [[ -f "$TFTP_DIR/boot.ipxe" ]] && ! grep -q 'netboot-chain.sh' "$TFTP_DIR/boot.ipxe" 2>/dev/null; then
        sudo cp -f "$TFTP_DIR/boot.ipxe" "$TFTP_DIR/boot.ipxe.pre-maas" 2>/dev/null \
            && info "kept the previous single-payload boot.ipxe as boot.ipxe.pre-maas"
    fi
    chain_script | sed "s/@PORT@/$PORT/" | sudo tee "$TFTP_DIR/boot.ipxe" >/dev/null \
        || die "could not write $TFTP_DIR/boot.ipxe"
    info "chain installed: $TFTP_DIR/boot.ipxe -> http://<gw>:$PORT/maas/\${hostname}.ipxe"

    # 2. the unclaimed-node script, into the HTTP docroot (no sudo — it is ours).
    mkdir -p "$DOCROOT/maas" || die "could not create $DOCROOT/maas"
    default_script > "$DOCROOT/maas/default.ipxe" \
        || die "could not write $DOCROOT/maas/default.ipxe"
    info "unclaimed-node script: $DOCROOT/maas/default.ipxe (says why, then stops)"

    # 3. sanity: is the docroot actually being served? A chain to a 404 is the same
    # silent timeout we are here to remove, so check it now rather than at boot.
    if command -v curl >/dev/null; then
        gw="$(virsh -c qemu:///system net-dumpxml "$NET" 2>/dev/null \
              | sed -nE "s/.*<ip address='([^']+)'.*/\1/p" | head -1)"
        if [[ -n "$gw" ]]; then
            if curl -fsS --max-time 5 -o /dev/null "http://$gw:$PORT/maas/default.ipxe" 2>/dev/null; then
                info "verified: http://$gw:$PORT/maas/default.ipxe is served (the nodes can reach the chain)"
            else
                printf 'netboot-chain: WARNING — http://%s:%s/maas/default.ipxe is NOT reachable.\n' "$gw" "$PORT" >&2
                printf '  The chain is installed but the nodes will fetch a 404 and stop at the iPXE\n' >&2
                printf '  shell. Start the payload server first: ( cd ../virtualbmc-ipmi-lab && ./setup-pxe-net.sh )\n' >&2
            fi
        fi
    fi
    ;;

emit-chain)
    # The chain script on stdout, port already substituted, no sudo and no writes.
    # build-verifying-rom.sh compiles this INTO the firmware, so the ROM resolves
    # the per-node script itself instead of TFTP-fetching boot.ipxe first. Both
    # paths must ask the same question of the control plane, so they read it from
    # here rather than each keeping a copy that can drift.
    chain_script | sed "s/@PORT@/$PORT/"
    ;;

emit-default)
    # The unclaimed-node script on stdout — the sudo-free half of `install`, for
    # refreshing the docroot copy after this file's wording changes.
    default_script
    ;;

show)
    printf '== %s/boot.ipxe ==\n' "$TFTP_DIR"
    sudo cat "$TFTP_DIR/boot.ipxe" 2>/dev/null || printf '(absent or unreadable)\n'
    printf '\n== %s/maas/ ==\n' "$DOCROOT"
    ls -1 "$DOCROOT/maas" 2>/dev/null || printf '(absent)\n'
    ;;

*)
    cat >&2 <<EOF
netboot-chain.sh — point the PXE network at the control plane's per-node scripts

  install       replace the network's baked boot.ipxe with a chain that resolves
                maas/\${hostname}.ipxe -> maas/\${net0/mac}.ipxe -> maas/default.ipxe
  emit-chain    print that chain script on stdout (what build-verifying-rom.sh
                compiles into the firmware); no sudo, no writes
  emit-default  print the unclaimed-node script on stdout (refresh the docroot
                copy without sudo: emit-default > <docroot>/maas/default.ipxe)
  show          print what is installed

Without this, every node on $NET boots whatever single payload setup-pxe-net.sh
baked in, and the per-node scripts the deploy drivers write are never fetched.

  TFTP_DIR=$TFTP_DIR   docroot=$DOCROOT   port=$PORT
EOF
    exit 2 ;;
esac
