#!/usr/bin/env bash
# Export: bring up a lab, emit --format lxc-yaml, verify the YAML has the
# expected instance keys.  Full re-import round-trip is exercised manually
# in MANUAL_TESTING (requires `lxc launch --yaml` or stdin-config form).

set -euo pipefail
. "$(dirname -- "${BASH_SOURCE[0]}")/lib.sh"

require_lxd_or_incus
require_cmd jq

lab="xp$$"
cfg="$(mktemp --suffix=.toml)"
out="$(mktemp --suffix=.yaml)"
trap 'rm -f "$cfg" "$out"; cleanup_lab "$lab"' EXIT

cat > "$cfg" <<EOF
[lab]
name = "${lab}"

[[instance]]
name  = "one"
image = "images:alpine/latest"

[[instance]]
name  = "two"
image = "images:alpine/latest"
EOF

note "up"
"$LAB_LXD" up --config "$cfg"

note "export --format lxc-yaml"
"$LAB_LXD" export "$lab" --format lxc-yaml > "$out"

note "verify YAML structure"
grep -q "^# generated by"       "$out" || fail "missing generator comment"
grep -q "^# instance: lab-${lab}-one" "$out" || fail "missing instance-one header"
grep -q "^# instance: lab-${lab}-two" "$out" || fail "missing instance-two header"
grep -q "^---$"                 "$out" || fail "missing YAML document separator"
# `config show --expanded` always includes these top-level keys.
grep -q "^config:"              "$out" || fail "missing config: key"
grep -q "^devices:"             "$out" || fail "missing devices: key"
# Label round-trip — expanded config should carry user.lab-create.lab.
grep -q "user.lab-create.lab"   "$out" || fail "expanded YAML lost user.lab-create.lab"

note "YAML shape OK — $(wc -l <"$out") lines"
pass "export --format lxc-yaml OK"
