"""Phase 4 — Podman service topology wizard.

Generates a TOML (lab + [[service]]) for lab-podman.sh up --config.
"""

from __future__ import annotations

from textual.app import ComposeResult
from textual.widgets import Checkbox, Input, Label, Select

from lab_tui.screens.wizards.base import WizardModal

_MANAGERS = [
    ("plain (rootless podman run)", "plain"),
    ("pod (shared namespace)",       "pod"),
    ("quadlet (systemd-user unit)",  "quadlet"),
]


class PodmanServiceWizard(WizardModal):
    TITLE = "Phase 4 — New Podman topology"

    def compose_form(self) -> ComposeResult:
        yield Label("Lab name *", classes="field-label")
        yield Input(placeholder="my-lab", id="f-lab")

        yield Label("Manager", classes="field-label")
        yield Select(_MANAGERS, id="f-manager", value="plain")

        yield Label("Service name *", classes="field-label")
        yield Input(placeholder="web", id="f-svc")

        yield Label("Image *", classes="field-label")
        yield Input(placeholder="nginx:alpine", id="f-image")

        yield Label("Ports (host:container, comma-sep)", classes="field-label")
        yield Input(placeholder="8080:80", id="f-ports")

        yield Label("Volumes (src:dst, comma-sep)", classes="field-label")
        yield Input(placeholder="/data:/data:ro", id="f-vols")

        yield Label("Environment vars (KEY=VAL, comma-sep)", classes="field-label")
        yield Input(placeholder="DB_URL=postgres://...", id="f-env")

        yield Label("Pod name (pod manager only)", classes="field-label")
        yield Input(placeholder="my-pod", id="f-pod")

        yield Label("Network name (optional)", classes="field-label")
        yield Input(placeholder="front", id="f-net")

        yield Checkbox("Generate quadlet unit file", False, id="f-quadlet-note")

    def _default_save_path(self) -> str:
        lab = self._val("f-lab", self) or "my-lab"
        return f"examples/podman-{lab}.toml"

    def generate_toml(self) -> str:
        lab     = self._val("f-lab",     self) or "<lab>"
        manager = self._sel("f-manager", self) or "plain"
        svc     = self._val("f-svc",     self) or "<service>"
        image   = self._val("f-image",   self) or "<image>"
        ports   = self._val("f-ports",   self)
        vols    = self._val("f-vols",    self)
        env     = self._val("f-env",     self)
        pod     = self._val("f-pod",     self)
        net     = self._val("f-net",     self)
        quadlet_note = self._chk("f-quadlet-note", self)

        lines = [
            "# Generated by lab-create TUI — Phase 4 Podman topology wizard",
            f"# Usage: lab-podman.sh up   --config <this-file>  (manager={manager})",
            "#        lab-podman.sh down --lab " + lab,
        ]
        if manager == "quadlet" or quadlet_note:
            lines.append(
                "#        lab-podman.sh generate --config <this-file>  (write unit files)"
            )
        lines += [
            "",
            "[lab]",
            f'name = "{lab}"',
            "",
        ]

        # Pod block (pod manager only)
        if manager == "pod" and pod:
            lines += [
                "[[pod]]",
                f'name = "{pod}"',
                "",
            ]

        lines += [
            "[[service]]",
            f'name   = "{svc}"',
            f'engine = "podman"',
            f'image  = "{image}"',
        ]
        if manager == "pod" and pod:
            lines.append(f'pod    = "{pod}"')
        if net:
            lines.append(f'networks = ["{net}"]')
        if ports:
            port_list = ", ".join(f'"{p.strip()}"' for p in ports.split(",") if p.strip())
            lines.append(f"ports  = [{port_list}]")
        if vols:
            vol_list = ", ".join(f'"{v.strip()}"' for v in vols.split(",") if v.strip())
            lines.append(f"volumes = [{vol_list}]")
        if env:
            pairs = {}
            for item in env.split(","):
                item = item.strip()
                if "=" in item:
                    k, _, v = item.partition("=")
                    pairs[k.strip()] = v.strip()
            if pairs:
                lines.append("environment = { "
                             + ", ".join(f'{k} = "{v}"' for k, v in pairs.items())
                             + " }")
        return "\n".join(lines) + "\n"
