"""Phase 3 — Docker service topology wizard.

Generates a TOML (lab + network + [[service]]) for lab-docker.sh up --config.
"""

from __future__ import annotations

from textual.app import ComposeResult
from textual.widgets import Input, Label

from lab_tui.screens.wizards.base import WizardModal


class DockerServiceWizard(WizardModal):
    TITLE = "Phase 3 — New Docker topology"

    def compose_form(self) -> ComposeResult:
        yield Label("Lab name *", classes="field-label")
        yield Input(placeholder="my-lab", id="f-lab")

        yield Label("Service name *", classes="field-label")
        yield Input(placeholder="web", id="f-svc")

        yield Label("Image *", classes="field-label")
        yield Input(placeholder="nginx:alpine", id="f-image")

        yield Label("Ports (host:container, comma-sep)", classes="field-label")
        yield Input(placeholder="8080:80,8443:443", id="f-ports")

        yield Label("Environment vars (KEY=VAL, comma-sep)", classes="field-label")
        yield Input(placeholder="FOO=bar,BAZ=qux", id="f-env")

        yield Label("Volumes (src:dst, comma-sep)", classes="field-label")
        yield Input(placeholder="/data:/data", id="f-vols")

        yield Label("Network name (default: front)", classes="field-label")
        yield Input(placeholder="front", id="f-net")

        yield Label("Additional service (name:image, optional)", classes="field-label")
        yield Input(placeholder="db:postgres:16-alpine", id="f-svc2")

    def _default_save_path(self) -> str:
        lab = self._val("f-lab", self) or "my-lab"
        return f"examples/docker-{lab}.toml"

    def generate_toml(self) -> str:
        lab   = self._val("f-lab",   self) or "<lab>"
        svc   = self._val("f-svc",   self) or "<service>"
        image = self._val("f-image", self) or "<image>"
        ports = self._val("f-ports", self)
        env   = self._val("f-env",   self)
        vols  = self._val("f-vols",  self)
        net   = self._val("f-net",   self) or "front"
        svc2  = self._val("f-svc2",  self)

        lines = [
            "# Generated by lab-create TUI — Phase 3 Docker topology wizard",
            "# Usage: lab-docker.sh up   --config <this-file>",
            "#        lab-docker.sh down --lab " + lab,
            "",
            "[lab]",
            f'name = "{lab}"',
            "",
            f"[network.{net}]",
            'driver = "bridge"',
            "",
            "[[service]]",
            f'name     = "{svc}"',
            f'image    = "{image}"',
            f'networks = ["{net}"]',
        ]
        if ports:
            port_list = ", ".join(f'"{p.strip()}"' for p in ports.split(",") if p.strip())
            lines.append(f"ports    = [{port_list}]")
        if env:
            pairs = {}
            for item in env.split(","):
                item = item.strip()
                if "=" in item:
                    k, _, v = item.partition("=")
                    pairs[k.strip()] = v.strip()
            if pairs:
                lines.append("environment = { "
                             + ", ".join(f'{k} = "{v}"' for k, v in pairs.items())
                             + " }")
        if vols:
            vol_list = ", ".join(f'"{v.strip()}"' for v in vols.split(",") if v.strip())
            lines.append(f"volumes  = [{vol_list}]")

        # Optional second service
        if svc2 and ":" in svc2:
            parts = svc2.split(":", 1)
            svc2_name  = parts[0].strip()
            svc2_image = parts[1].strip()
            lines += [
                "",
                "[[service]]",
                f'name     = "{svc2_name}"',
                f'image    = "{svc2_image}"',
                f'networks = ["{net}"]',
            ]

        return "\n".join(lines) + "\n"
