"""Phase 1 — Chroot create wizard.

Generates a [[chroot]] TOML for lab-chroot.sh create --config <file>.
"""

from __future__ import annotations

from pathlib import Path

from textual.app import ComposeResult
from textual.widgets import Checkbox, Input, Label, Select

from lab_tui.screens.wizards.base import WizardModal, _toml_str

_BACKENDS = [("debootstrap", "debootstrap"), ("dnf / yum", "dnf"), ("host-copy", "host-copy")]
_DISTROS  = [
    ("Debian", "debian"), ("Ubuntu", "ubuntu"), ("Kali Linux", "kali"),
    ("Rocky Linux", "rocky"), ("AlmaLinux", "alma"), ("Fedora", "fedora"),
]
_ARCHES  = [
    ("x86_64", "x86_64"), ("aarch64", "aarch64"), ("armv7l", "armv7l"),
    ("ppc64le", "ppc64le"), ("riscv64", "riscv64"), ("s390x", "s390x"),
]
_MANAGERS = [("none (bare chroot)", "none"), ("schroot", "schroot"), ("nspawn", "nspawn")]
_INITS    = [("none", ""), ("busybox", "busybox"), ("systemd", "systemd")]


class ChrootWizard(WizardModal):
    TITLE = "Phase 1 — New chroot"

    def compose_form(self) -> ComposeResult:
        yield Label("Name *", classes="field-label")
        yield Input(placeholder="my-chroot", id="f-name")

        yield Label("Backend *", classes="field-label")
        yield Select(_BACKENDS, id="f-backend", value="debootstrap")

        yield Label("Distro", classes="field-label")
        yield Select(_DISTROS, id="f-distro", value="debian", allow_blank=True)

        yield Label("Suite / release", classes="field-label")
        yield Input(placeholder="bookworm", id="f-suite")

        yield Label("Architecture", classes="field-label")
        yield Select(_ARCHES, id="f-arch", value="x86_64")

        yield Label("Target path", classes="field-label")
        yield Input(placeholder="/var/chroots/<name>", id="f-target")

        yield Label("Manager", classes="field-label")
        yield Select(_MANAGERS, id="f-manager", value="none")

        yield Label("Extra packages (comma-separated)", classes="field-label")
        yield Input(placeholder="curl,vim", id="f-pkgs")

        yield Label("init_script (for export-initrd)", classes="field-label")
        yield Select(_INITS, id="f-init", allow_blank=True)

    def _default_save_path(self) -> str:
        name = self._val("f-name", self) or "my-chroot"
        return f"examples/chroot-{name}.toml"

    def run_hint(self, path: Path) -> str:
        return (
            f"# TOML saved to: {path}\n"
            f"#\n"
            f"# Run this to create the chroot:\n\n"
            f"sudo phase1-chroot/lab-chroot.sh create --config {path}\n\n"
            f"# Then enter it:\n"
            f"sudo phase1-chroot/lab-chroot.sh enter "
            f"{self._val('f-name', self) or '<name>'}\n"
        )

    def generate_toml(self) -> str:
        name    = self._val("f-name",    self) or "<name>"
        backend = self._sel("f-backend", self) or "debootstrap"
        distro  = self._sel("f-distro",  self)
        suite   = self._val("f-suite",   self)
        arch    = self._sel("f-arch",    self) or "x86_64"
        target  = self._val("f-target",  self) or f"/var/chroots/{name}"
        manager = self._sel("f-manager", self) or "none"
        pkgs    = self._val("f-pkgs",    self)
        init    = self._sel("f-init",    self)

        # F-01: escape all free-text values before embedding in TOML strings.
        lines = [
            "# Generated by lab-create TUI — Phase 1 chroot wizard",
            "# Usage: sudo lab-chroot.sh create --config <this-file>",
            "",
            "[[chroot]]",
            f'name    = "{_toml_str(name)}"',
            f'backend = "{_toml_str(backend)}"',
        ]
        if distro:
            lines.append(f'distro  = "{_toml_str(distro)}"')
        if suite:
            lines.append(f'suite   = "{_toml_str(suite)}"')
        lines.append(f'arch    = "{_toml_str(arch)}"')
        lines.append(f'target  = "{_toml_str(target)}"')
        lines.append(f'manager = "{_toml_str(manager)}"')
        if pkgs:
            pkg_list = ", ".join(f'"{_toml_str(p.strip())}"' for p in pkgs.split(",") if p.strip())
            lines.append(f"include = [{pkg_list}]")
        if init:
            lines.append(f'init_script = "{_toml_str(init)}"')
        return "\n".join(lines) + "\n"
