"""Phase 5 — LXD/Incus instance wizard.

Generates a TOML (lab + [[instance]]) for lab-lxd.sh up --config.
"""

from __future__ import annotations

from pathlib import Path

from textual.app import ComposeResult
from textual.widgets import Input, Label, Select

from lab_tui.screens.wizards.base import WizardModal

_TYPES  = [("container", "container"), ("vm (hardware-virtualised)", "vm")]
_ARCHES = [
    ("x86_64 (default)", "x86_64"), ("aarch64", "aarch64"),
    ("armv7l", "armv7l"), ("ppc64le", "ppc64le"),
    ("riscv64", "riscv64"), ("s390x", "s390x"),
]
_IMAGES = [
    ("images:alpine/latest",            "images:alpine/latest"),
    ("images:debian/bookworm",          "images:debian/bookworm"),
    ("images:ubuntu/24.04",             "images:ubuntu/24.04"),
    ("images:rockylinux/9",             "images:rockylinux/9"),
    ("images:fedora/41",                "images:fedora/41"),
    ("custom (enter below)",            ""),
]


class LXDInstanceWizard(WizardModal):
    TITLE = "Phase 5 — New LXD/Incus instance"

    def compose_form(self) -> ComposeResult:
        yield Label("Lab name *", classes="field-label")
        yield Input(placeholder="my-lab", id="f-lab")

        yield Label("Instance name *", classes="field-label")
        yield Input(placeholder="shell", id="f-name")

        yield Label("Type", classes="field-label")
        yield Select(_TYPES, id="f-type", value="container")

        yield Label("Image (quick-select)", classes="field-label")
        yield Select(_IMAGES, id="f-image-sel", value="images:alpine/latest",
                     allow_blank=True)

        yield Label("Custom image alias (overrides above)", classes="field-label")
        yield Input(placeholder="images:kali/rolling", id="f-image-custom")

        yield Label("Architecture (optional)", classes="field-label")
        yield Select(_ARCHES, id="f-arch", allow_blank=True)

        yield Label("Storage pool (optional)", classes="field-label")
        yield Input(placeholder="default", id="f-storage")

        yield Label("Profiles (comma-separated)", classes="field-label")
        yield Input(placeholder="default", id="f-profiles")

        yield Label("Project (optional)", classes="field-label")
        yield Input(placeholder="my-project", id="f-project")

        yield Label("Config key=val pairs (comma-sep)", classes="field-label")
        yield Input(placeholder='security.secureboot=false', id="f-config")

    def _default_save_path(self) -> str:
        lab = self._val("f-lab", self) or "my-lab"
        return f"examples/lxd-{lab}.toml"

    def run_hint(self, path: Path) -> str:
        lab = self._val("f-lab", self) or "<lab>"
        return (
            f"# TOML saved to: {path}\n"
            f"#\n"
            f"# Bring up the lab:\n\n"
            f"phase5-lxd/lab-lxd.sh up   --config {path}\n\n"
            f"# List instances:\n\n"
            f"phase5-lxd/lab-lxd.sh list --lab {lab}\n\n"
            f"# Tear down:\n\n"
            f"phase5-lxd/lab-lxd.sh down --lab {lab}\n"
        )

    def generate_toml(self) -> str:
        lab          = self._val("f-lab",          self) or "<lab>"
        name         = self._val("f-name",         self) or "<name>"
        itype        = self._sel("f-type",         self) or "container"
        image_sel    = self._sel("f-image-sel",    self)
        image_custom = self._val("f-image-custom", self)
        arch         = self._sel("f-arch",         self)
        storage      = self._val("f-storage",      self)
        profiles_raw = self._val("f-profiles",     self)
        project      = self._val("f-project",      self)
        config_raw   = self._val("f-config",       self)

        # Custom image overrides the quick-select if filled in.
        image = image_custom if image_custom else (image_sel or "images:alpine/latest")

        lines = [
            "# Generated by lab-create TUI — Phase 5 LXD/Incus wizard",
            "# Usage: lab-lxd.sh up   --config <this-file>",
            "#        lab-lxd.sh down --lab " + lab,
            "",
            "[lab]",
            f'name = "{lab}"',
            "",
            "[[instance]]",
            f'name  = "{name}"',
            f'type  = "{itype}"',
            f'image = "{image}"',
        ]
        if arch:
            lines.append(f'arch  = "{arch}"')
        if storage:
            lines.append(f'storage = "{storage}"')
        if project:
            lines.append(f'project = "{project}"')
        if profiles_raw:
            profile_list = ", ".join(
                f'"{p.strip()}"' for p in profiles_raw.split(",") if p.strip()
            )
            lines.append(f"profiles = [{profile_list}]")
        if config_raw:
            pairs = {}
            for item in config_raw.split(","):
                item = item.strip()
                if "=" in item:
                    k, _, v = item.partition("=")
                    pairs[k.strip()] = v.strip()
            if pairs:
                lines.append("config = { "
                             + ", ".join(f'"{k}" = "{v}"' for k, v in pairs.items())
                             + " }")

        return "\n".join(lines) + "\n"
