"""Phase 2 — QEMU VM create wizard.

Generates a [[vm]] TOML for lab-vm.sh create --config <file>.
"""

from __future__ import annotations

from textual.app import ComposeResult
from textual.widgets import Checkbox, Input, Label, Select

from lab_tui.screens.wizards.base import WizardModal

_BACKENDS = [
    ("disk-image (cloud image)", "disk-image"),
    ("kernel+initrd (direct boot)", "kernel+initrd"),
    ("from-chroot (Phase 1 tree)", "from-chroot"),
    ("pxe-install (UEFI PXE, root)", "pxe-install"),
]
_DISTROS = [
    ("Debian", "debian"), ("Ubuntu", "ubuntu"), ("Alpine", "alpine"),
    ("Kali Linux", "kali"), ("Rocky Linux", "rocky"),
]
_ARCHES  = [
    ("x86_64", "x86_64"), ("aarch64", "aarch64"), ("armv7l", "armv7l"),
    ("ppc64le", "ppc64le"), ("riscv64", "riscv64"), ("s390x", "s390x"),
]
_MEMORY  = [("128M", "128M"), ("256M", "256M"), ("512M", "512M"),
            ("1G", "1G"), ("2G", "2G"), ("4G", "4G"), ("8G", "8G")]
_CPUS    = [("1", "1"), ("2", "2"), ("4", "4"), ("8", "8")]


class VMWizard(WizardModal):
    TITLE = "Phase 2 — New QEMU VM"

    def compose_form(self) -> ComposeResult:
        yield Label("Name *", classes="field-label")
        yield Input(placeholder="my-vm", id="f-name")

        yield Label("Backend *", classes="field-label")
        yield Select(_BACKENDS, id="f-backend", value="disk-image")

        yield Label("Distro (disk-image)", classes="field-label")
        yield Select(_DISTROS, id="f-distro", value="debian", allow_blank=True)

        yield Label("Suite / release", classes="field-label")
        yield Input(placeholder="bookworm / 24.04 / 3.20 …", id="f-suite")

        yield Label("Architecture", classes="field-label")
        yield Select(_ARCHES, id="f-arch", value="x86_64")

        yield Label("Memory", classes="field-label")
        yield Select(_MEMORY, id="f-memory", value="2G")

        yield Label("CPUs", classes="field-label")
        yield Select(_CPUS, id="f-cpus", value="2")

        yield Label("Lab name (optional)", classes="field-label")
        yield Input(placeholder="my-lab", id="f-lab")

        yield Checkbox("microvm (fast boot, virtio-mmio)", False, id="f-microvm")
        yield Checkbox("Disable cloud-init",               False, id="f-nocloudinit")

    def _default_save_path(self) -> str:
        name = self._val("f-name", self) or "my-vm"
        return f"examples/vm-{name}.toml"

    def generate_toml(self) -> str:
        name      = self._val("f-name",    self) or "<name>"
        backend   = self._sel("f-backend", self) or "disk-image"
        distro    = self._sel("f-distro",  self)
        suite     = self._val("f-suite",   self)
        arch      = self._sel("f-arch",    self) or "x86_64"
        memory    = self._sel("f-memory",  self) or "2G"
        cpus      = self._sel("f-cpus",    self) or "2"
        lab       = self._val("f-lab",     self)
        microvm   = self._chk("f-microvm",     self)
        no_ci     = self._chk("f-nocloudinit", self)

        lines = [
            "# Generated by lab-create TUI — Phase 2 VM wizard",
            "# Usage: lab-vm.sh create --config <this-file>",
            "#        lab-vm.sh start  <name>",
            "",
            "[[vm]]",
            f'name    = "{name}"',
            f'backend = "{backend}"',
        ]
        if distro:
            lines.append(f'distro  = "{distro}"')
        if suite:
            lines.append(f'suite   = "{suite}"')
        lines.append(f'arch    = "{arch}"')
        lines.append(f'memory  = "{memory}"')
        lines.append(f'cpus    = {cpus}')
        if lab:
            lines.append(f'lab     = "{lab}"')
        if microvm:
            lines.append("microvm = true")
        if no_ci:
            lines.append("cloud_init = false")
        return "\n".join(lines) + "\n"
