#!/usr/bin/env bash
# build-config-patch.sh — the same-length config edit the config-edit track applies
# to a config file INSIDE a UKI's .initrd (Spike 10).
#
# Derived at run time, never cached (the repo's rule): reads the target config
# (etc/conf) OUT of the UKI's own .initrd with objcopy + cpio, and produces a
# SAME-LENGTH replacement by flipping its value byte — a "fix a boot-blocking
# config value in place" edit that needs no cpio rebuild. It emits:
#   <out.fth>    Forth compiling the replacement into the dictionary, plus the
#                member name and a bogus name for the NO-MEMBER control:
#                  config-name  ( -- adr len )  the member to patch (etc/conf)
#                  config-new   ( -- adr len )  the same-length replacement bytes
#                  config-bogus ( -- adr len )  a name not in the archive
#   <out.newbin> the replacement bytes, for the host oracle to compare against
#
# Usage: build-config-patch.sh <uki.efi> <out.fth> <out.newbin>
set -eu
UKI="${1:?usage: build-config-patch.sh <uki.efi> <out.fth> <out.newbin>}"
OUTF="${2:?usage}"; OUTB="${3:?usage}"
MEMBER=etc/conf
command -v objcopy >/dev/null || { echo "objcopy not installed (binutils)" >&2; exit 1; }
command -v cpio    >/dev/null || { echo "cpio not installed (GNU cpio)" >&2; exit 1; }
command -v od      >/dev/null || { echo "od not installed (coreutils)" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 not installed" >&2; exit 1; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
objcopy -O binary --only-section=.initrd "$UKI" "$TMP/initrd" 2>/dev/null || { echo "objcopy could not extract .initrd from $UKI" >&2; exit 1; }
cpio -i --to-stdout "$MEMBER" < "$TMP/initrd" > "$TMP/old" 2>/dev/null || { echo "cpio could not extract $MEMBER from the initrd" >&2; exit 1; }
oldsz="$(stat -c%s "$TMP/old")"
(( oldsz >= 2 )) || { echo "$MEMBER is $oldsz bytes — too short to hold a value to flip" >&2; exit 1; }

# same-length replacement: flip the value byte (the char before a trailing newline,
# else the last byte): '1'->'0', anything else->'1', so it always actually changes.
python3 "$TMP/flip.py" "$TMP/old" "$OUTB" 2>/dev/null || python3 -c '
import sys
d=bytearray(open(sys.argv[1],"rb").read())
i=len(d)-1
if i>=0 and d[i]==0x0a: i-=1
i=max(i,0)
d[i]=0x30 if d[i]==0x31 else 0x31
open(sys.argv[2],"wb").write(bytes(d))
' "$TMP/old" "$OUTB"
newsz="$(stat -c%s "$OUTB")"
(( newsz == oldsz )) || { echo "the replacement is $newsz bytes, the original $oldsz — the edit must be same-length" >&2; exit 1; }
cmp -s "$TMP/old" "$OUTB" && { echo "the replacement is identical to the original — the edit would not be observable" >&2; exit 1; }

{ echo '\ GENERATED by fixtures/config-edit/build-config-patch.sh — do not edit.'
  echo 'hex'
  echo 'create config-new-data'
  od -An -v -tx1 "$OUTB" | tr -s ' ' '\n' | grep -vE '^$' | awk '{printf "%s c, ", $1}'
  echo
  printf ': config-new   ( -- adr len )  config-new-data %x ;\n' "$newsz"
  printf ': config-name  ( -- adr len )  s" %s" ;\n' "$MEMBER"
  echo ': config-bogus ( -- adr len )  s" no/such/file" ;'
} > "$OUTF"
# VERIFY THE OUTCOME: the emitted Forth must encode EXACTLY newsz bytes (od without
# -v would collapse repeats and silently drop some).
nbytes="$(grep -oE '[0-9a-f]{2} c,' "$OUTF" | wc -l)"
(( nbytes == newsz )) || { echo "the emitted Forth encodes $nbytes bytes, expected $newsz" >&2; exit 1; }
