#!/usr/bin/env bash
# openbios-regen-tested-tree.sh — regenerate examples/openbios-the-rival-that-shipped/
# patches/TESTED-TREE.patch from a working tree.
#
# WHY THIS IS A SCRIPT AND NOT A PARAGRAPH. The patch is generated, and a
# generated artifact whose procedure lives in prose drifts from its procedure --
# the same reason tools/lib/verb-probe.sh is shared rather than copied. The one
# step a human would forget is the `git add -N`, without which `git diff` omits
# every file the divergence CREATES; that omission is exactly how
# arch/amd64/boot.h stayed out of the record while arch/amd64/boot.c included it.
#
# THE Arch-tested: LINE IS AN ARGUMENT, NOT A CONSTANT. Stamping it
# unconditionally would make it a cached fact about a tree that just changed --
# bug class #1. It has to be passed, which means someone decided it. Omit it and
# tools/check-patch-scope.sh fails loudly until the tracks are actually run.
set -euo pipefail
usage() {
    cat <<'USAGE'
openbios-regen-tested-tree.sh --arch-tested "ARCH..." [--workdir DIR]

Regenerates patches/TESTED-TREE.patch: the cumulative divergence from the pinned
upstream commit to WORKDIR, including files the divergence creates.

  --arch-tested "x86 amd64 ppc"   arches the tracks were RUN on for this tree.
                                  Required: it is a claim, so it is a decision.
  --workdir DIR                   default $HOME/openbios-lab/openbios

Refuses to run unless WORKDIR is at the pin recorded in build-openbios.sh.
USAGE
}
ARCHES=""; WD="$HOME/openbios-lab/openbios"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --arch-tested) ARCHES="${2:-}"; shift 2 ;;
        --workdir)     WD="${2:-}"; shift 2 ;;
        -h|--help)     usage; exit 0 ;;
        *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done
HERE="$(cd "$(dirname "$0")/.." && pwd)"
LAB="$HERE/examples/openbios-the-rival-that-shipped"
OUT="$LAB/patches/TESTED-TREE.patch"

[[ -n "$ARCHES" ]] || { echo "ERROR: --arch-tested is required; see --help for why" >&2; exit 2; }
[[ -d "$WD/.git" ]] || { echo "ERROR: $WD is not a git clone" >&2; exit 2; }

PIN="$(sed -n 's/^OPENBIOS_PIN=\([0-9a-f]\{40\}\)$/\1/p' "$LAB/build-openbios.sh" | head -1)"
[[ -n "$PIN" ]] || { echo "ERROR: no OPENBIOS_PIN in build-openbios.sh" >&2; exit 2; }
AT="$(git -C "$WD" rev-parse HEAD)"
if [[ "$AT" != "$PIN" ]]; then
    echo "ERROR: $WD is at ${AT:0:7}, the pin is ${PIN:0:7}." >&2
    echo "       A diff taken against a different base is not this lab's divergence." >&2
    exit 1
fi

# Look before overwriting: say what is there now and what replaces it.
if [[ -f "$OUT" ]]; then
    echo "==> existing: $(grep -c '^+++ b/' "$OUT") files, $(wc -l < "$OUT") lines"
fi

# `git add -N` is the whole point: without it, git diff shows no created files.
mapfile -t UNTRACKED < <(git -C "$WD" status --porcelain | awk '/^\?\?/{print $2}')
if (( ${#UNTRACKED[@]} )); then
    echo "==> including ${#UNTRACKED[@]} created file(s): ${UNTRACKED[*]}"
    git -C "$WD" add -N -- "${UNTRACKED[@]}"
fi
TMP="$(mktemp)"
{
    cat <<HDR
This file is GENERATED by tools/openbios-regen-tested-tree.sh. Do not hand-edit.

The CUMULATIVE divergence from the pinned upstream commit to the tree the smoke
tracks are run against -- the x86 revival, the amd64 port, and the 2026-08
fixes, in one diff. build-openbios.sh applies THIS.

patches/NN-*.patch are the RECORD, one annotated change each. They are not
applied and are not a linear series: each was extracted as a diff against a tree
that already had the others, so applying 01..N to a pristine pin lands roughly
half of them. tools/check-patch-hygiene.sh A6 binds the record to this file, so
the two cannot drift apart in either direction.

Base: openbios $PIN
Arch-tested: $ARCHES

HDR
    git -C "$WD" diff
} > "$TMP"
if (( ${#UNTRACKED[@]} )); then
    git -C "$WD" reset -q -- "${UNTRACKED[@]}"
fi
mv "$TMP" "$OUT"
echo "==> wrote $OUT: $(grep -c '^+++ b/' "$OUT") files, $(wc -l < "$OUT") lines, Arch-tested: $ARCHES"
