#!/usr/bin/env python3
"""paths.py — learning-paths generator + coverage/link linter.

The orthogonal companion to link_check.py.  examples/00-INDEX.md catalogues the
labs *by phase/substrate* (a reference axis); this tool renders a *learning* axis
— ordered, dependency-aware PATHS (a syllabus, for mentees) and themed, unordered
COLLECTIONS (a browse index, for the self-directed) — from a single hand-edited
source of truth, examples/learning-paths.toml.

Two jobs:

  1. RENDER (default) — read the TOML and (re)generate, under
     examples/learning-paths/:
       - README.md          the hub: how-to-use, rubric, path index, collections,
                            capstones.
       - path-<id>.md       one per path: the ordered step table with, per step,
                            "what you'll learn" + an *observable* checkpoint.
     Every generated file opens with a DO-NOT-EDIT banner; edit the TOML instead.

  2. CHECK (--check, the CI gate) — three guards, any failure ⇒ exit non-zero:
       a. REF RESOLUTION   every lab/member/branch/capstone ref resolves to a
                           real path (same two-base rule link_check.py uses).
       b. COVERAGE         every lab unit under examples/ (each own-subdir lab +
                           each grouping bucket + each standalone root .toml)
                           appears in >=1 path step or collection — the anti-drift
                           guard: a new lab nobody routed into a journey trips CI.
                           Intentional exclusions go in [meta].coverage_exempt
                           WITH a reason, so the gate stays honest.
       c. FRESHNESS        re-render in memory and diff against the on-disk files;
                           a hand-edit (or a stale checkout) fails ("run render").

Lab refs in the TOML are written RELATIVE TO examples/ (e.g. "chroot-breakout/",
"chroot-examples/chroot-debian-bookworm.toml", or an out-of-tree hand-walk as
"../micro-linux/hand-walk/") — exactly the forms 00-INDEX already uses.  The
renderer, writing into examples/learning-paths/, prepends "../" so every emitted
link resolves for link_check.py too.

Usage:
  tools/paths.py                 # render the learning-paths/ docs from the TOML
  tools/paths.py render          # (same)
  tools/paths.py --check         # CI gate: refs resolve + full coverage + fresh
  tools/paths.py --json          # machine-readable check report

Exit status: non-zero if --check finds any failure (refs / coverage / freshness).
Defaults: --root auto-detected via .git; source = examples/learning-paths.toml;
          output = examples/learning-paths/.
"""
from __future__ import annotations

import argparse
import difflib
import json
import subprocess
import sys
import tomllib
from pathlib import Path

# ── Locations (relative to the repo root) ───────────────────────────────────
EXAMPLES_DIR = "examples"
SOURCE_TOML = "examples/learning-paths.toml"          # source of truth
OUTPUT_DIR = "examples/learning-paths"                 # generated docs
BANNER = ("<!-- GENERATED by tools/paths.py from examples/learning-paths.toml "
          "— do not edit by hand; edit the TOML and run `tools/paths.py render`. -->")

# A lab unit is "covered" if it and a ref overlap in the path hierarchy.  Docs
# and the generated output dir are never lab units; anything else intentionally
# unrouted must be named in [meta].coverage_exempt.
_NON_LAB_NAMES = {"README.md"}  # inside OUTPUT_DIR we never treat this as a unit


def find_repo_root(start: Path) -> Path:
    """Walk up from `start` until a .git dir is found; fall back to start."""
    for p in [start, *start.parents]:
        if (p / ".git").exists():
            return p
    return start


def list_files(root: Path) -> list[Path]:
    """git-tracked + untracked-but-not-ignored files (so .gitignore is honored);
    filesystem-walk fallback outside a git checkout.  (Same contract as
    link_check.list_files — kept local so this tool has no import coupling.)"""
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "ls-files", "--cached", "--others",
             "--exclude-standard", "-z"],
            capture_output=True, check=True, text=True,
        ).stdout
        return [f for f in (root / r for r in out.split("\0") if r) if f.is_file()]
    except (subprocess.CalledProcessError, FileNotFoundError):
        return [p for p in root.rglob("*") if p.is_file() and ".git" not in p.parts]


# ── TOML load ────────────────────────────────────────────────────────────────
def load_spec(root: Path) -> dict:
    src = root / SOURCE_TOML
    if not src.exists():
        sys.exit(f"error: source of truth not found: {SOURCE_TOML}")
    with src.open("rb") as fh:
        return tomllib.load(fh)


# ── Ref resolution (examples/-relative, two-base like link_check) ────────────
def strip_slash(ref: str) -> str:
    return ref.rstrip("/")


def resolve_ref(root: Path, ref: str) -> Path | None:
    """A lab ref is relative to examples/.  Return the resolved path if it exists
    (as file OR dir), else None.  A leading `#anchor`/URL is never a lab ref."""
    r = strip_slash(ref.split("#", 1)[0].strip())
    if not r:
        return None
    cand = (root / EXAMPLES_DIR / r).resolve()
    if cand.exists():
        return cand
    alt = (root / r).resolve()             # tolerate a repo-root-relative ref
    return alt if alt.exists() else None


def link_for(ref: str) -> str:
    """Turn an examples/-relative ref into a link that works from a file inside
    examples/learning-paths/ — one dir deeper, so prepend '../'."""
    return "../" + ref.split("#", 1)[0].strip()


def cell(s: str) -> str:
    """Escape a value for a Markdown table cell: a raw '|' (e.g. a shell pipe in
    a `code span`) would otherwise be read as a column separator."""
    return s.replace("|", "\\|")


# ── Collect every ref the TOML mentions (for coverage + resolution checks) ───
def iter_refs(spec: dict):
    """Yield (kind, ref) for every lab-bearing field in the spec."""
    for p in spec.get("path", []):
        for s in p.get("step", []):
            yield ("step", s["lab"])
        for b in p.get("branch", []):
            yield ("branch", b["lab"])
    for c in spec.get("collection", []):
        for m in c.get("members", []):
            yield ("member", m)
    for cap in spec.get("capstone", []):
        yield ("capstone", cap["lab"])


# ── Coverage universe: the lab units that must each be routed somewhere ──────
def lab_units(root: Path) -> list[str]:
    """Immediate children of examples/ that count as a lab: a subdir containing a
    README.md, or a standalone *.toml spec.  Returned as examples/-relative
    strings (dirs without trailing slash).  The generated OUTPUT_DIR is skipped."""
    ex = root / EXAMPLES_DIR
    out_name = Path(OUTPUT_DIR).name
    units = []
    for child in sorted(ex.iterdir()):
        if child.name == out_name:
            continue
        if child.is_dir() and (child / "README.md").exists():
            units.append(child.name)
        elif child.is_file() and child.suffix == ".toml":
            units.append(child.name)
    return units


def is_covered(unit: str, refs: list[str]) -> bool:
    """Covered if any ref overlaps the unit in the path hierarchy: the ref is the
    unit, sits inside it, or the unit sits inside the ref."""
    u = strip_slash(unit)
    for ref in refs:
        r = strip_slash(ref.split("#", 1)[0].strip())
        if r == u or r.startswith(u + "/") or u.startswith(r + "/"):
            return True
    return False


# ── Rendering ────────────────────────────────────────────────────────────────
def _path_title(spec: dict, pid: str) -> str:
    for p in spec.get("path", []):
        if p["id"] == pid:
            return p["title"]
    return pid


def render_path(spec: dict, p: dict) -> str:
    """One path-<id>.md: the ordered syllabus with observable checkpoints."""
    L = [BANNER, ""]
    L.append(f"# {p['title']} {p.get('difficulty', '')}".rstrip())
    L.append("")
    L.append(f"**Goal.** {p['goal']}")
    L.append("")
    meta_bits = []
    if p.get("audience"):
        meta_bits.append(f"**Audience:** {p['audience']}")
    if p.get("est"):
        meta_bits.append(f"**Effort:** {p['est']}")
    prereqs = p.get("prereqs", [])
    if prereqs:
        links = " · ".join(f"[{_path_title(spec, q)}](path-{q}.md)" for q in prereqs)
        meta_bits.append(f"**Prerequisites:** {links}")
    else:
        meta_bits.append("**Prerequisites:** none")
    L.append("  \n".join(meta_bits))
    L.append("")
    L.append("| # | Lab | You'll learn | Checkpoint (observable) |")
    L.append("|---|---|---|---|")
    for i, s in enumerate(p.get("step", []), 1):
        tags = " ".join(s.get("tags", []))
        lab_cell = f"[`{strip_slash(s['lab'])}`]({link_for(s['lab'])})"
        if tags:
            lab_cell += f" {tags}"
        chk = s["checkpoint"]
        if s.get("verify_cmd"):
            marker = s.get("verify_marker", "")
            chk += f"<br>`{s['verify_cmd']}`" + (f" → `{marker}`" if marker else "")
        L.append(f"| {i} | {cell(lab_cell)} | {cell(s['learn'])} | {cell(chk)} |")
    L.append("")
    branches = p.get("branch", [])
    if branches:
        L.append("### Optional side-quests")
        L.append("")
        for b in branches:
            L.append(f"- [`{strip_slash(b['lab'])}`]({link_for(b['lab'])}) — {b['why']}")
        L.append("")
    L.append("---")
    L.append("")
    L.append("← back to the [learning-paths hub](README.md) · "
             "reference catalog: [`00-INDEX.md`](../00-INDEX.md)")
    L.append("")
    return "\n".join(L)


def render_hub(spec: dict) -> str:
    meta = spec.get("meta", {})
    L = [BANNER, ""]
    L.append("# Learning paths & collections")
    L.append("")
    L.append("A *learning* view over the labs in [`../`](../) — the orthogonal "
             "companion to the by-phase reference catalog "
             "[`00-INDEX.md`](../00-INDEX.md). Two ways in:")
    L.append("")
    L.append("- **Paths** — *ordered, dependency-aware syllabi.* Start at step 1 "
             "and climb; each step names what you'll learn and a concrete, "
             "**observable checkpoint** (a command output, a file, a boot banner) "
             "that proves you got it. Built for **mentees** and anyone ramping a "
             "new area.")
    L.append("- **Collections** — *themed, unordered bundles.* Browse everything "
             "of a kind (\"every Matt-Might lab\", \"every libvirt lab\"). Built "
             "for **self-directed** exploration.")
    L.append("")
    L.append("A lab happily appears in several paths and collections — there's "
             "more than one good route through it.")
    L.append("")
    # Rubric
    L.append("## Rubric")
    L.append("")
    L.append("**Difficulty** (the *learning* cost): "
             + " · ".join(meta.get("difficulty_levels", []))
             + ".  **Effort** (rough hands-on time): "
             + " · ".join(meta.get("time_buckets", [])) + ".")
    L.append("")
    L.append("These are orthogonal to 00-INDEX's *run-cost* tags, which are "
             "carried through unchanged: 🔑 needs sudo/root · 🐌 runs under TCG "
             "(slow, no HW) · 🪶 rootless · 🔗 unified (feeds several phases). "
             "Safety flags (⚠️ throwaway only · 🔒 offensive tooling — authorized "
             "targets only) travel with the labs that carry them.")
    L.append("")
    L.append("> **Maintained by a generator.** This file and every `path-*.md` "
             "are rendered from [`../learning-paths.toml`](../learning-paths.toml) "
             "by [`tools/paths.py`](../../tools/paths.py). Don't hand-edit them — "
             "edit the TOML and run `tools/paths.py render`. `tools/paths.py "
             "--check` gates CI: every lab is routed into ≥1 path/collection, "
             "every ref resolves, and the docs match the source.")
    L.append("")
    # Paths index
    L.append("## Paths")
    L.append("")
    L.append("| Path | Diff | Effort | Goal |")
    L.append("|---|---|---|---|")
    for p in spec.get("path", []):
        L.append(f"| [{p['title']}](path-{p['id']}.md) | {p.get('difficulty','')} "
                 f"| {p.get('est','')} | {p['goal']} |")
    L.append("")
    # Collections
    L.append("## Collections")
    L.append("")
    for c in spec.get("collection", []):
        members = " · ".join(
            f"[`{strip_slash(m)}`]({link_for(m)})" for m in c.get("members", []))
        L.append(f"### {c['title']}")
        L.append("")
        L.append(f"*{c['theme']}*")
        L.append("")
        L.append(members)
        L.append("")
    # Capstones
    capstones = spec.get("capstone", [])
    if capstones:
        L.append("## Capstones")
        L.append("")
        L.append("Pan-phase demos that belong to no single journey — run them once "
                 "the paths have given you the pieces:")
        L.append("")
        for cap in capstones:
            L.append(f"- [`{strip_slash(cap['lab'])}`]({link_for(cap['lab'])}) — "
                     f"{cap['note']}")
        L.append("")
    L.append("---")
    L.append("")
    L.append("*Extending this?* Add a `[[path]]`/`[[collection]]` to "
             "[`../learning-paths.toml`](../learning-paths.toml) — every `lab`/"
             "`member` is an `examples/`-relative ref, and every `checkpoint` must "
             "be *observable* (mirror the style of each lab's `MANUAL_TESTING.md` "
             "success signatures). Then `tools/paths.py render` && `tools/paths.py "
             "--check`.")
    L.append("")
    return "\n".join(L)


def render_all(spec: dict) -> dict[str, str]:
    """Return {relative_output_path: content} for every file we generate."""
    files = {f"{OUTPUT_DIR}/README.md": render_hub(spec)}
    for p in spec.get("path", []):
        files[f"{OUTPUT_DIR}/path-{p['id']}.md"] = render_path(spec, p)
    return files


# ── Commands ─────────────────────────────────────────────────────────────────
def cmd_render(root: Path, spec: dict) -> int:
    out_dir = root / OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    generated = render_all(spec)
    expected_names = {Path(rel).name for rel in generated}
    # Write / update.
    for rel, content in generated.items():
        (root / rel).write_text(content, encoding="utf-8")
    # Prune stale path-*.md left over from a removed path.
    removed = []
    for f in out_dir.glob("path-*.md"):
        if f.name not in expected_names:
            f.unlink()
            removed.append(f.name)
    print(f"rendered {len(generated)} file(s) into {OUTPUT_DIR}/")
    for rel in sorted(generated):
        print(f"  • {rel}")
    for name in sorted(removed):
        print(f"  ✂ removed stale {OUTPUT_DIR}/{name}")
    return 0


def cmd_check(root: Path, spec: dict, as_json: bool) -> int:
    problems: dict[str, list] = {"unresolved_refs": [], "uncovered": [], "stale_files": []}

    # a. Ref resolution.
    for kind, ref in iter_refs(spec):
        if resolve_ref(root, ref) is None:
            problems["unresolved_refs"].append({"kind": kind, "ref": ref})

    # b. Coverage.
    all_refs = [ref for _, ref in iter_refs(spec)]
    all_refs += [cap["lab"] for cap in spec.get("capstone", [])]  # capstones count
    exempt = set(spec.get("meta", {}).get("coverage_exempt", {}).keys()) \
        if isinstance(spec.get("meta", {}).get("coverage_exempt"), dict) \
        else set(spec.get("meta", {}).get("coverage_exempt", []))
    for unit in lab_units(root):
        if unit in exempt:
            continue
        if not is_covered(unit, all_refs):
            problems["uncovered"].append(unit)

    # c. Freshness.
    generated = render_all(spec)
    out_dir = root / OUTPUT_DIR
    for rel, content in generated.items():
        disk = root / rel
        on_disk = disk.read_text(encoding="utf-8") if disk.exists() else ""
        if on_disk != content:
            diff = "\n".join(difflib.unified_diff(
                on_disk.splitlines(), content.splitlines(),
                fromfile=f"{rel} (on disk)", tofile=f"{rel} (expected)", lineterm=""))
            problems["stale_files"].append({"file": rel, "diff": diff[:2000]})
    expected_names = {Path(rel).name for rel in generated}
    if out_dir.exists():
        for f in out_dir.glob("path-*.md"):
            if f.name not in expected_names:
                problems["stale_files"].append(
                    {"file": f"{OUTPUT_DIR}/{f.name}", "diff": "stale: no such path in the TOML"})

    ok = not any(problems.values())

    if as_json:
        print(json.dumps({"ok": ok, **problems}, indent=2))
        return 0 if ok else 1

    print("== learning-paths check ==")
    if problems["unresolved_refs"]:
        print(f"  ✗ {len(problems['unresolved_refs'])} unresolved ref(s):")
        for r in problems["unresolved_refs"]:
            print(f"      [{r['kind']}] {r['ref']}  → no such path under examples/")
    else:
        print("  ✓ every lab/member/branch/capstone ref resolves")
    if problems["uncovered"]:
        print(f"  ✗ {len(problems['uncovered'])} lab unit(s) not routed into any "
              f"path/collection (add a step/member, or exempt with a reason):")
        for u in problems["uncovered"]:
            print(f"      • {u}")
    else:
        print("  ✓ every lab unit is covered by ≥1 path or collection")
    if problems["stale_files"]:
        print(f"  ✗ {len(problems['stale_files'])} generated file(s) out of date — "
              f"run `tools/paths.py render`:")
        for s in problems["stale_files"]:
            print(f"      • {s['file']}")
    else:
        print("  ✓ generated docs match the source of truth")
    return 0 if ok else 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", default="render", choices=["render", "check"],
                    help="render (default) the docs, or check the source")
    ap.add_argument("--check", action="store_true", help="alias for the `check` command (CI gate)")
    ap.add_argument("--json", action="store_true", help="machine-readable check report")
    ap.add_argument("--root", type=Path, default=None, help="repo root (default: auto-detect via .git)")
    args = ap.parse_args(argv)

    root = (args.root or find_repo_root(Path(__file__).resolve().parent)).resolve()
    spec = load_spec(root)

    if args.check or args.command == "check":
        return cmd_check(root, spec, args.json)
    return cmd_render(root, spec)


if __name__ == "__main__":
    sys.exit(main())
